use crate::rules::{Finding, Severity};
use std::fmt::Write;

pub fn to_markdown(findings: &[Finding]) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# Pinocchio Sentinel Security Report\n\n");

    // Summary
    let high_count = findings
        .iter()
        .filter(|f| f.severity == Severity::HIGH)
        .count();
    let medium_count = findings
        .iter()
        .filter(|f| f.severity == Severity::MEDIUM)
        .count();
    let warn_count = findings
        .iter()
        .filter(|f| f.severity == Severity::WARN)
        .count();

    write!(
        md,
        "## Summary\n\n\
         | Severity | Count |\n\
         |----------|-------|\n\
         | HIGH | {} |\n\
         | MEDIUM | {} |\n\
         | WARN | {} |\n\
         | **Total** | **{}** |\n\n",
        high_count,
        medium_count,
        warn_count,
        findings.len()
    )
    .unwrap();

    // Findings
    if findings.is_empty() {
        md.push_str("## Findings\n\nNo security issues found.\n\n");
        return md;
    }

    md.push_str("## Findings\n\n");

    // Group by handler
    let mut handlers: std::collections::HashMap<String, Vec<&Finding>> =
        std::collections::HashMap::new();
    for finding in findings {
        handlers
            .entry(finding.handler.clone())
            .or_default()
            .push(finding);
    }

    for (handler, handler_findings) in &handlers {
        writeln!(md, "### Handler: `{}`\n", handler).unwrap();

        for finding in handler_findings {
            let severity_icon = match finding.severity {
                Severity::HIGH => "🔴",
                Severity::MEDIUM => "🟡",
                _ => "🔵",
            };

            writeln!(
                md,
                "#### {} {} {}\n",
                severity_icon, finding.rule_id, finding.message
            )
            .unwrap();

            if let Some(line) = finding.line_number {
                writeln!(md, "- **Line:** {}", line).unwrap();
            }

            if let Some(ref fix) = finding.fix_suggestion {
                writeln!(md, "- **Fix:** {}", fix).unwrap();
            }

            md.push('\n');
        }
    }

    // Footer
    md.push_str("---\n\n");
    md.push_str("*Generated by Pinocchio Sentinel - Static Analysis for Solana Programs*\n");

    md
}
